### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [DeweyReed/ClipboardCleaner#10]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by DeweyReed** [comment]
Thank you! I'll try to add the screenshots in the next release. PR is also welcome. :D

**Comment by DeweyReed** [comment]
It's now available.
