### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rikishi0071** [DeweyReed/ClipboardCleaner#11]
Hi! It's an absolutely amazing app which is must-have on all Android devices! I love it! I'd like to translate it to Russian. Are you planning to set up something like Crowdin or do I manually need to translate strings.xml and send you? Thank you!

**Comment by DeweyReed** [comment]
@rikishi0071 

I don't plan to set up a translation service for now since it's too complicated for this little app.

If you're familiar with Android development, you're welcome to translate strings.xml and open a PR. :D

Thank you!

**Comment by rikishi0071** [comment]
Hi! I've created PR with Russian translation for strings.xml.
Look at: https://github.com/DeweyReed/ClipboardCleaner/pull/12/files

By the way, is there any way to translate title, short_description and full_description of the app which are displayed on F-Droid store app page?

**Comment by DeweyReed** [comment]
Thank you!

The PR needs some change, and I've added details to its comment.

As for F-Droid translation, you can try this link: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/. You can also leave the translation here. I'll deal with it along with other info(like screenshots) later anyway.

**Comment by rikishi0071** [comment]
I've changed PR, look at: https://github.com/DeweyReed/ClipboardCleaner/pull/13/

F-Droid description translations:

title:
ЧисткаБуфера
short_description:
Проверяйте и очищайте Ваш буфер обмена
full_description:
Насколько Вы осведомлены, содержимое буфера обмена Android и его изменения доступны с помощью любого приложения, что является дырой в безопасности, если Вам это небезразлично. Любое приложение может получить Ваш скопированный пароль, номера кредитных карт и так далее.

Хоть ЧисткаБуфера и не может защитить Ваши пароли от доступа со стороны любого приложения, но зато предоставляет Вам несколько способов проверки и очистки буфера обмена.

**Comment by DeweyReed** [comment]
I've merged the PR.

I'll add F-Droid app info later this month and publish a new release.

Thank you again! Have a great day. :D

**Comment by DeweyReed** [comment]
1.5.1 has added the translation.

However, F-Droid doesn't recognize the title and full description translation. I'll look into this problem in the next release.

**Comment by DeweyReed** [comment]
I notice that the translation for the title and full description are available in the F-Droid app. Mission accomplished. 😄
