### ISSUE TITLE
F-droid inclusion?

### ISSUE THREAD

**Issue by thoroughbredthrowaway** [DeweyReed/ClipboardCleaner#2]
Hi, I've tried to submit your application to [F-Droid](https://f-droid.org) [a free (as in freedom) software repository]. One of the [inclusion criteria](https://f-droid.org/wiki/page/Inclusion_Policy) appears to be that the authors of the software know of the inclusion and support it. So I hereby ask you if you would support such an inclusion.

See the issue: https://gitlab.com/fdroid/rfp/issues/835#note_130926425

**Comment by thoroughbredthrowaway** [comment]
@DeweyReed ?

**Comment by DeweyReed** [comment]
@thoroughbredthrowaway I'm here and you're welcome to submit this app F-droid. 

I don't know why Github didn't email me about this issue until you @ me, but I'm sorry to reply so late.

**Comment by DeweyReed** [comment]
@IzzySoft Fantastic.

I'll open another issue to fix the security issue.

Thank you for helping bring this app to F-Droid😉
