### ISSUE TITLE
增加自动清理剪贴板功能

### ISSUE THREAD

**Issue by amokiel** [DeweyReed/ClipboardCleaner#27]
目前主要是用它的两个桌面小组件查看和清理剪贴板，如果再有个自动清理功能就完全足够了。看到一个同类型的剪贴板工具Clipeus，是通过获取通知权限，关闭屏幕之后会自动清理当前剪切板内容。这个方法感觉还不错，不过那个应用的功能经常失效，不会自动清理。希望可以考虑增加一个自动清理的功能。多谢开发者，您辛苦了！

**Comment by DeweyReed** [comment]
和 #21 重复。

从Android 10开始，就无法通过简单手段做到了。
据说Android 13系统自带一个类似的功能。

**Comment by DeweyReed** [comment]
@clbclby 之后会增加一个对Android 13的支持。此外暂时没有更多的计划了。
