### ISSUE TITLE
Service does not work

### ISSUE THREAD

**Issue by zerotaste** [DeweyReed/ClipboardCleaner#7]
I'm using samsung keyboard on android 9 and I can see clipboard entries thrugh its menu after service says clipboard is cleaned.

**Comment by DeweyReed** [comment]
Does samsung keyboard show the a history of clipboard entry? If so, it stores all entries and this app can do nothing about it.

**Comment by zerotaste** [comment]
I get it. Thanks for quick answer.

Отправлено из мобильного клиента ProtonMail

-------- Исходное сообщение --------
Вкл 1 сент. 2019 г., 4:54, DeweyReed пишет:

**Comment by DeweyReed** [comment]
OK. I'm closing this issue. Feel free to reopen it if you have other problems.
