### ISSUE TITLE
Reset timer when text is copied

### ISSUE THREAD

**Issue by 35609902357** [DeweyReed/ClipboardCleaner#8]
The current behavior is to start as many timers as many times text is copied, so if I set the timer to 60 seconds, then I copy something and then something else after 50 seconds, the clipboard is cleared 10 seconds after the new copy because of the first timer, and the second one goes in action after 50 additional seconds. The new timer should always replace the previous one, there is no point in having many timers.

**Comment by DeweyReed** [comment]
This is a bug. Thanks for telling me. I'll fix it in the next release.

**Comment by DeweyReed** [comment]
1.4.2 should fix this bug.
