### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ghost** [DeweyReed/ClipboardCleaner#9]
Like the F-Droid app itself, this could use a Dark Mode.

**Comment by DeweyReed** [comment]
Good idea. I'll add it in the next release.

**Comment by Kukulkan2019** [comment]
Great, it's a good little app... funny in the past years I could never find
the 'clipboard', it's not in settings, but at least now I can clear it
although I rarely put anything in it...




Brennan Mulrennan on LinkedIn, Gravatar & WordPress.com...♞
